title = "Budget Tracking: {budget_item}"
body = """
## Budget Item Information
Item Name: {budget_item}
Category: {category}

## Financial Details
Estimated Cost: {estimated_cost}
Actual Cost: {actual_cost}
Variance: {variance}

## Timeline
Start Date: {start_date}
End Date: {end_date}

## Status
{status}

## Funding Source
{funding_source}

## Approvals
{approvals}

## Notes
{notes}

## Attachments
{attachments}
"""

[fields]
budget_item = { type = "string", required = true }
category = { type = "string", required = true }
estimated_cost = { type = "float", required = true }
actual_cost = { type = "float", required = false }
variance = { type = "float", required = false }
start_date = { type = "date", required = true }
end_date = { type = "date", required = true }
status = { type = "string", required = true }
funding_source = { type = "string", required = true }
approvals = { type = "string", required = false }
notes = { type = "string", required = false }
attachments = { type = "string", required = false }
